# revision 30211
# category Package
# catalog-ctan /fonts/raleway
# catalog-date 2013-05-02 20:57:12 +0200
# catalog-license ofl
# catalog-version 1.0
Name:		texlive-raleway
Version:	1.0
Release:	1
Summary:	Use Raleway with TeX(-alike) systems
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/fonts/raleway
License:	OFL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/raleway.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/raleway.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
The package provides the Raleway family in an easy to use way.
For XeLaTeX and LuaLaTeX users the original OpenType fonts are
used. The entire font family is included.

%post
    %{_sbindir}/texlive.post

%postun
    if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_7mkq5h.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_bzmckq.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_ioyy6d.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_k2dfwc.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_keo5xw.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_l5jmzb.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_nli7k3.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_oaj2jl.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_sor5xn.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_sp3cim.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_uagyv3.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_umxzao.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_yqxcf3.enc
%{_texmfdistdir}/fonts/map/dvips/raleway/Raleway.map
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Black.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Bold.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-ExtraBold.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-ExtraLight.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Light.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Medium.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Regular.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-SemiBold.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Thin.otf
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ts1.tfm
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Black.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Bold.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-ExtraBold.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-ExtraLight.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Light.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Medium.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Regular.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-SemiBold.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Thin.pfb
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-osf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-osf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-osf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-osf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-osf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ts1.vf
%{_texmfdistdir}/tex/latex/raleway/.sty
%{_texmfdistdir}/tex/latex/raleway/LY1-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/LY1Raleway-OsF.fd
%{_texmfdistdir}/tex/latex/raleway/LY1Raleway-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/LY1Raleway-TOsF.fd
%{_texmfdistdir}/tex/latex/raleway/OT1-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/OT1Raleway-OsF.fd
%{_texmfdistdir}/tex/latex/raleway/OT1Raleway-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/OT1Raleway-TOsF.fd
%{_texmfdistdir}/tex/latex/raleway/T1-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/T1Raleway-OsF.fd
%{_texmfdistdir}/tex/latex/raleway/T1Raleway-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/T1Raleway-TOsF.fd
%{_texmfdistdir}/tex/latex/raleway/TS1-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/TS1Raleway-OsF.fd
%{_texmfdistdir}/tex/latex/raleway/TS1Raleway-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/TS1Raleway-TOsF.fd
%{_texmfdistdir}/tex/latex/raleway/raleway-type1-autoinst.sty
%{_texmfdistdir}/tex/latex/raleway/raleway.sty
%doc %{_texmfdistdir}/doc/latex/raleway/OFL.txt
%doc %{_texmfdistdir}/doc/latex/raleway/README
%doc %{_texmfdistdir}/doc/latex/raleway/raleway-otf-specimen.pdf
%doc %{_texmfdistdir}/doc/latex/raleway/raleway-otf-specimen.tex
%doc %{_texmfdistdir}/doc/latex/raleway/raleway-type1-specimen.pdf
%doc %{_texmfdistdir}/doc/latex/raleway/raleway-type1-specimen.tex
%doc %{_texmfdistdir}/doc/latex/raleway/raleway.pdf
%doc %{_texmfdistdir}/doc/latex/raleway/raleway.tex

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar fonts tex doc %{buildroot}%{_texmfdistdir}
