# revision 31969
# category Package
# catalog-ctan /fonts/raleway
# catalog-date 2013-06-19 01:04:08 +0200
# catalog-license ofl
# catalog-version 1.0
Name:		texlive-raleway
Version:	1.0
Release:	7
Summary:	Use Raleway with TeX(-alike) systems
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/fonts/raleway
License:	OFL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/raleway.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/raleway.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
The package provides the Raleway family in an easy to use way.
For XeLaTeX and LuaLaTeX users the original OpenType fonts are
used. The entire font family is included.

%post
    %{_sbindir}/texlive.post

%postun
    if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_2bcjq6.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_biciir.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_bzmckq.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_f3uqdf.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_gvxmk7.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_ioname.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_k2dfwc.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_mgzrni.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_mzuigi.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_oaf34p.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_pcwse4.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_sor5xn.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_u6n666.enc
%{_texmfdistdir}/fonts/enc/dvips/raleway/a_yqxcf3.enc
%{_texmfdistdir}/fonts/map/dvips/raleway/Raleway.map
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Black-Italic.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Black.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Bold-Italic.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Bold.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-ExtraBold-Italic.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-ExtraBold.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-ExtraLight-Italic.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-ExtraLight.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Light-Italic.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Light.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Medium-Italic.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Medium.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Regular-Italic.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Regular.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-SemiBold-Italic.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-SemiBold.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Thin-Italic.otf
%{_texmfdistdir}/fonts/opentype/theleagueofmoveabletype/raleway/Raleway-Thin.otf
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Black.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-BlackItalic.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Bold.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-BoldItalic.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-ExtraBold.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-ExtraLight.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Italic.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Light.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-LightItalic.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Medium.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-MediumItalic.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Regular.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-SemiBold.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-Thin.pfb
%{_texmfdistdir}/fonts/type1/theleagueofmoveabletype/raleway/Raleway-ThinItalic.pfb
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Black-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BlackItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Bold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-BoldItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraBoldItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLight-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ExtraLightItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Italic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Light-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-LightItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Medium-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-MediumItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Regular-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-SemiBoldItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-Thin-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/theleagueofmoveabletype/raleway/Raleway-ThinItalic-tosf-ts1.vf
%{_texmfdistdir}/tex/latex/raleway/LY1Raleway-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/LY1Raleway-TOsF.fd
%{_texmfdistdir}/tex/latex/raleway/OT1Raleway-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/OT1Raleway-TOsF.fd
%{_texmfdistdir}/tex/latex/raleway/T1Raleway-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/T1Raleway-TOsF.fd
%{_texmfdistdir}/tex/latex/raleway/TS1Raleway-TLF.fd
%{_texmfdistdir}/tex/latex/raleway/TS1Raleway-TOsF.fd
%{_texmfdistdir}/tex/latex/raleway/raleway-type1-autoinst.sty
%{_texmfdistdir}/tex/latex/raleway/raleway.sty
%doc %{_texmfdistdir}/doc/latex/raleway/OFL.txt
%doc %{_texmfdistdir}/doc/latex/raleway/README
%doc %{_texmfdistdir}/doc/latex/raleway/raleway-otf-specimen.pdf
%doc %{_texmfdistdir}/doc/latex/raleway/raleway-otf-specimen.tex
%doc %{_texmfdistdir}/doc/latex/raleway/raleway-type1-specimen.pdf
%doc %{_texmfdistdir}/doc/latex/raleway/raleway-type1-specimen.tex
%doc %{_texmfdistdir}/doc/latex/raleway/raleway.pdf
%doc %{_texmfdistdir}/doc/latex/raleway/raleway.tex

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar fonts tex doc %{buildroot}%{_texmfdistdir}
